const fallbackView={center:[-5.1,-45.2],zoom:6};
const map=L.map('map',{zoomControl:true}).setView(fallbackView.center,fallbackView.zoom);
const basemaps={osm:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}),light:L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors &copy; CARTO'})};
let currentBasemap=basemaps.osm.addTo(map);L.control.scale({imperial:false,position:'bottomleft'}).addTo(map);
let maranhao=null,municipios=null,maranhaoBounds=null,localGeojson=null;
let mapMode='identify';
const maranhaoCheckbox=document.getElementById('layer-maranhao'),municipiosCheckbox=document.getElementById('layer-municipios');
function formatArea(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';}
function municipioPopup(p){return `<div class="municipio-popup"><strong>${p.NM_MUN||'Município'}</strong><br>Código IBGE: ${p.CD_MUN||'—'}<br>UF: ${p.SIGLA_UF||'MA'}<br>Área: ${formatArea(p.AREA_KM2)} km²<br><small>Fonte: IBGE — Malha Municipal 2025</small></div>`;}
function estadoPopup(p){return `<div class="municipio-popup"><strong>${p.NM_UF||'Maranhão'}</strong><br>Código da UF: ${p.CD_UF||'—'}<br>Sigla: ${p.SIGLA_UF||'MA'}<br>Região: ${p.NM_REGIAO||'Nordeste'}<br>Área: ${formatArea(p.AREA_KM2)} km²<br><small>Fonte: IBGE — Malha Territorial 2025</small></div>`;}
function genericPopup(p){const entries=Object.entries(p||{}).slice(0,12);return entries.length?`<div class="generic-popup">${entries.map(([k,v])=>`<strong>${String(k).replace(/[<>]/g,'')}:</strong> ${String(v??'—').replace(/</g,'&lt;').replace(/>/g,'&gt;')}<br>`).join('')}</div>`:'<strong>Feição sem atributos</strong>';}
function bindModeAwarePopup(layer,html){layer.bindPopup(html);layer.on('click',e=>{if(mapMode==='measure'){if(layer.isPopupOpen())layer.closePopup();L.DomEvent.stopPropagation(e);addMeasurePoint(e.latlng);}});}
fetch('data/geojson/maranhao_limite_2025_web.geojson').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(data=>{maranhao=L.geoJSON(data,{style:{color:'#123f3b',weight:3,opacity:.95,fillColor:'#6eb8ad',fillOpacity:.04},onEachFeature:(f,l)=>bindModeAwarePopup(l,estadoPopup(f.properties||{}))});if(maranhaoCheckbox.checked)maranhao.addTo(map);maranhaoBounds=maranhao.getBounds();if(maranhaoBounds.isValid())map.fitBounds(maranhaoBounds,{padding:[15,15]});}).catch(error=>{console.error(error);maranhaoCheckbox.checked=false;maranhaoCheckbox.disabled=true;});
fetch('data/geojson/municipios_ma_2025_web.geojson').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(data=>{municipios=L.geoJSON(data,{style:{color:'#397c73',weight:.8,fillColor:'#6eb8ad',fillOpacity:.16},onEachFeature:(f,l)=>{bindModeAwarePopup(l,municipioPopup(f.properties||{}));l.on({mouseover:e=>e.target.setStyle({weight:2,fillOpacity:.30}),mouseout:e=>municipios.resetStyle(e.target)});}});if(municipiosCheckbox.checked)municipios.addTo(map);if(!maranhaoBounds){maranhaoBounds=municipios.getBounds();if(maranhaoBounds.isValid())map.fitBounds(maranhaoBounds,{padding:[15,15]});}if(maranhao&&map.hasLayer(maranhao))maranhao.bringToFront();}).catch(error=>{console.error(error);municipiosCheckbox.checked=false;municipiosCheckbox.disabled=true;});
const campus=L.circleMarker([-2.558,-44.308],{radius:8,color:'#123f3b',weight:2,fillOpacity:.75});bindModeAwarePopup(campus,'<b>Ponto demonstrativo</b><br>Camada temporária a ser substituída por unidades acadêmicas validadas.');campus.addTo(map);

document.querySelectorAll('input[name="basemap"]').forEach(r=>r.addEventListener('change',e=>{map.removeLayer(currentBasemap);currentBasemap=basemaps[e.target.value].addTo(map);currentBasemap.bringToBack();}));
maranhaoCheckbox.addEventListener('change',e=>{if(!maranhao)return;e.target.checked?maranhao.addTo(map):map.removeLayer(maranhao);if(e.target.checked)maranhao.bringToFront();});
municipiosCheckbox.addEventListener('change',e=>{if(!municipios)return;e.target.checked?municipios.addTo(map):map.removeLayer(municipios);if(maranhao&&map.hasLayer(maranhao))maranhao.bringToFront();});
document.getElementById('layer-campus').addEventListener('change',e=>e.target.checked?campus.addTo(map):map.removeLayer(campus));
document.getElementById('btn-home').onclick=()=>maranhaoBounds&&maranhaoBounds.isValid()?map.fitBounds(maranhaoBounds,{padding:[15,15]}):map.setView(fallbackView.center,fallbackView.zoom);
map.on('mousemove',e=>document.getElementById('coords').textContent=`Lat: ${e.latlng.lat.toFixed(5)} | Long: ${e.latlng.lng.toFixed(5)}`);

const fileInput=document.getElementById('geojson-file'),labStatus=document.getElementById('lab-status'),removeLocal=document.getElementById('btn-remove-geojson');
document.getElementById('btn-add-geojson').onclick=()=>fileInput.click();
function clearLocal(){if(localGeojson&&map.hasLayer(localGeojson))map.removeLayer(localGeojson);localGeojson=null;fileInput.value='';removeLocal.disabled=true;labStatus.textContent='Nenhum arquivo local carregado.';labStatus.className='lab-status';}
removeLocal.onclick=clearLocal;
fileInput.addEventListener('change',()=>{const file=fileInput.files[0];if(!file)return;if(file.size>10*1024*1024){labStatus.textContent='Arquivo acima de 10 MB. Otimize/generalize no QGIS antes do teste.';labStatus.className='lab-status error';fileInput.value='';return;}const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data||!['FeatureCollection','Feature','Point','MultiPoint','LineString','MultiLineString','Polygon','MultiPolygon','GeometryCollection'].includes(data.type))throw new Error('Estrutura GeoJSON não reconhecida');if(localGeojson&&map.hasLayer(localGeojson))map.removeLayer(localGeojson);localGeojson=L.geoJSON(data,{style:{color:'#a35f16',weight:2,fillColor:'#d79a52',fillOpacity:.25},pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:7,color:'#a35f16',weight:2,fillColor:'#d79a52',fillOpacity:.8}),onEachFeature:(f,l)=>bindModeAwarePopup(l,genericPopup(f.properties||{}))}).addTo(map);const b=localGeojson.getBounds();if(b.isValid())map.fitBounds(b,{padding:[20,20],maxZoom:15});removeLocal.disabled=false;const count=data.type==='FeatureCollection'?data.features.length:1;labStatus.textContent=`${file.name} · ${count} feição(ões) · camada local`;labStatus.className='lab-status success';if(maranhao&&map.hasLayer(maranhao))maranhao.bringToFront();}catch(err){console.error(err);clearLocal();labStatus.textContent='Erro: verifique se o arquivo é um GeoJSON válido em EPSG:4326.';labStatus.className='lab-status error';}};reader.onerror=()=>{labStatus.textContent='Erro ao ler o arquivo local.';labStatus.className='lab-status error';};reader.readAsText(file,'UTF-8');});

let points=[],measureLine=null,previewLine=null,labels=[],pointMarkers=[];
const measureButton=document.getElementById('btn-measure');
function distance(a,b){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng),s=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
function totalDistance(){let total=0;for(let i=1;i<points.length;i++)total+=distance(points[i-1],points[i]);return total;}
function clearMeasure(){points=[];if(measureLine){map.removeLayer(measureLine);measureLine=null;}if(previewLine){map.removeLayer(previewLine);previewLine=null;}labels.forEach(x=>map.removeLayer(x));labels=[];pointMarkers.forEach(x=>map.removeLayer(x));pointMarkers=[];}
function setMapMode(mode){mapMode=mode;map.closePopup();const container=map.getContainer();container.classList.toggle('measure-mode',mode==='measure');measureButton.classList.toggle('active-tool',mode==='measure');measureButton.textContent=mode==='measure'?'■ Finalizar medição':'↔ Medir distância';if(mode==='measure'){map.doubleClickZoom.disable();}else{map.doubleClickZoom.enable();if(previewLine){map.removeLayer(previewLine);previewLine=null;}}}
function addMeasurePoint(latlng){if(mapMode!=='measure')return;points.push(latlng);pointMarkers.push(L.circleMarker(latlng,{radius:4,color:'#123f3b',weight:2,fillColor:'#fff',fillOpacity:1,interactive:false}).addTo(map));if(measureLine)map.removeLayer(measureLine);measureLine=L.polyline(points,{color:'#123f3b',weight:3,dashArray:'7,6',interactive:false}).addTo(map);if(points.length>1){const total=totalDistance();labels.push(L.tooltip({permanent:true,direction:'top',className:'measure-label'}).setLatLng(latlng).setContent(total<1?`${(total*1000).toFixed(0)} m`:`${total.toFixed(2)} km`).addTo(map));}}
measureButton.onclick=()=>{if(mapMode==='measure'){setMapMode('identify');}else{clearMeasure();setMapMode('measure');}};
document.getElementById('btn-clear').onclick=()=>{clearMeasure();setMapMode('identify');};
map.on('click',e=>{if(mapMode==='measure')addMeasurePoint(e.latlng);});
map.on('mousemove',e=>{if(mapMode!=='measure'||points.length===0)return;if(previewLine)map.removeLayer(previewLine);previewLine=L.polyline([points[points.length-1],e.latlng],{color:'#397c73',weight:2,dashArray:'4,5',opacity:.7,interactive:false}).addTo(map);});
map.on('dblclick',e=>{if(mapMode!=='measure')return;L.DomEvent.preventDefault(e.originalEvent);L.DomEvent.stopPropagation(e);setMapMode('identify');});

const modal=document.getElementById('modal');document.getElementById('btn-geoai').onclick=()=>modal.hidden=false;document.getElementById('modal-close').onclick=()=>modal.hidden=true;modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true;});document.getElementById('menu-toggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');