const fallbackView={center:[-5.1,-45.2],zoom:6};
const map=L.map('map',{zoomControl:false}).setView(fallbackView.center,fallbackView.zoom);
const esriAttr='Tiles &copy; Esri — Source: Esri and data providers';
const grayBase=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}',{maxZoom:16,attribution:esriAttr});
const grayLabels=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer/tile/{z}/{y}/{x}',{maxZoom:16,attribution:esriAttr});
const sentinelAttr='EOxCloudless — EOX IT Services GmbH (Contains modified Copernicus Sentinel data 2025)';
const landsatAttr='Landsat imagery — Esri, USGS, NASA';
const LandsatImageLayer=L.GridLayer.extend({createTile(coords,done){const tile=document.createElement('img');tile.alt='';tile.setAttribute('role','presentation');const size=256,half=20037508.342789244,n=2**coords.z,span=(half*2)/n,minX=-half+coords.x*span,maxX=minX+span,maxY=half-coords.y*span,minY=maxY-span;const params=new URLSearchParams({f:'image',bbox:`${minX},${minY},${maxX},${maxY}`,bboxSR:'3857',imageSR:'3857',size:`${size},${size}`,format:'jpgpng',interpolation:'RSP_BilinearInterpolation'});tile.onload=()=>done(null,tile);tile.onerror=()=>done(new Error('Falha ao carregar imagem Landsat'),tile);tile.src=`https://landsat2.arcgis.com/arcgis/rest/services/Landsat8_Views/ImageServer/exportImage?${params.toString()}`;return tile;}});
const basemaps={
  osm:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}),
  imagery:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:esriAttr}),
  topographic:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:esriAttr}),
  opentopo:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'Map data &copy; OpenStreetMap contributors | SRTM | Map style &copy; OpenTopoMap (CC-BY-SA)'}),
  gray:L.layerGroup([grayBase,grayLabels]),
  sentinel:L.tileLayer('https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless-2025_3857/default/g/{z}/{y}/{x}.jpg',{minZoom:0,maxNativeZoom:14,maxZoom:18,attribution:sentinelAttr}),
  landsat:new LandsatImageLayer({tileSize:256,minZoom:2,maxZoom:16,attribution:landsatAttr})
};
let currentBasemap=basemaps.sentinel.addTo(map);L.control.scale({imperial:false,position:'bottomleft'}).addTo(map);
let maranhao=null,municipios=null,maranhaoBounds=null,localGeojson=null,mapMode='identify';
const maranhaoCheckbox=document.getElementById('layer-maranhao'),municipiosCheckbox=document.getElementById('layer-municipios');
function formatArea(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';}
function municipioPopup(p){return `<div class="municipio-popup"><strong>${p.NM_MUN||'Município'}</strong><br>Código IBGE: ${p.CD_MUN||'—'}<br>UF: ${p.SIGLA_UF||'MA'}<br>Área: ${formatArea(p.AREA_KM2)} km²<br><small>Fonte: IBGE — Malha Municipal 2025</small></div>`;}
function estadoPopup(p){return `<div class="municipio-popup"><strong>${p.NM_UF||'Maranhão'}</strong><br>Código da UF: ${p.CD_UF||'—'}<br>Sigla: ${p.SIGLA_UF||'MA'}<br>Região: ${p.NM_REGIAO||'Nordeste'}<br>Área: ${formatArea(p.AREA_KM2)} km²<br><small>Fonte: IBGE — Malha Territorial 2025</small></div>`;}
function genericPopup(p){const entries=Object.entries(p||{}).slice(0,12);return entries.length?`<div class="generic-popup">${entries.map(([k,v])=>`<strong>${String(k).replace(/[<>]/g,'')}:</strong> ${String(v??'—').replace(/</g,'&lt;').replace(/>/g,'&gt;')}<br>`).join('')}</div>`:'<strong>Feição sem atributos</strong>';}
function bindModeAwarePopup(layer,html){layer.bindPopup(html);layer.on('click',e=>{if(mapMode==='measure'||mapMode==='area'){if(layer.isPopupOpen())layer.closePopup();L.DomEvent.stopPropagation(e);mapMode==='measure'?addMeasurePoint(e.latlng):addAreaPoint(e.latlng);}});}
const layerStatus=document.getElementById('layer-status');
const campus=L.circleMarker([-2.558,-44.308],{radius:8,color:'#123f3b',weight:2,fillOpacity:.75});bindModeAwarePopup(campus,'<b>Ponto demonstrativo</b><br>Camada temporária a ser substituída por unidades acadêmicas validadas.');
async function loadMaranhao(){if(maranhao)return maranhao;layerStatus.textContent='Carregando limite do Maranhão…';try{const r=await fetch('data/geojson/maranhao_limite_2025_web.geojson');if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();maranhao=L.geoJSON(data,{style:{color:'#123f3b',weight:3,opacity:.95,fillColor:'#6eb8ad',fillOpacity:.04},onEachFeature:(f,l)=>bindModeAwarePopup(l,estadoPopup(f.properties||{}))});maranhaoBounds=maranhao.getBounds();layerStatus.textContent='Limite do Maranhão carregado.';layerStatus.className='lab-status success';return maranhao;}catch(error){console.error(error);maranhaoCheckbox.checked=false;layerStatus.textContent='Falha ao carregar o limite do Maranhão.';layerStatus.className='lab-status error';throw error;}}
async function loadMunicipios(){if(municipios)return municipios;layerStatus.textContent='Carregando municípios…';try{const r=await fetch('data/geojson/municipios_ma_2025_web.geojson');if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();municipios=L.geoJSON(data,{style:{color:'#397c73',weight:.8,fillColor:'#6eb8ad',fillOpacity:.16},onEachFeature:(f,l)=>{bindModeAwarePopup(l,municipioPopup(f.properties||{}));l.on({mouseover:e=>e.target.setStyle({weight:2,fillOpacity:.30}),mouseout:e=>municipios.resetStyle(e.target)});}});layerStatus.textContent='Municípios do Maranhão carregados.';layerStatus.className='lab-status success';return municipios;}catch(error){console.error(error);municipiosCheckbox.checked=false;layerStatus.textContent='Falha ao carregar os municípios.';layerStatus.className='lab-status error';throw error;}}
document.querySelectorAll('input[name="basemap"]').forEach(r=>r.addEventListener('change',e=>{map.removeLayer(currentBasemap);currentBasemap=basemaps[e.target.value].addTo(map);if(currentBasemap.bringToBack)currentBasemap.bringToBack();}));
maranhaoCheckbox.addEventListener('change',async e=>{if(e.target.checked){try{const l=await loadMaranhao();if(e.target.checked)l.addTo(map);if(maranhao&&map.hasLayer(maranhao))maranhao.bringToFront();}catch(_){}}else if(maranhao&&map.hasLayer(maranhao))map.removeLayer(maranhao);});
municipiosCheckbox.addEventListener('change',async e=>{if(e.target.checked){try{const l=await loadMunicipios();if(e.target.checked)l.addTo(map);if(maranhao&&map.hasLayer(maranhao))maranhao.bringToFront();}catch(_){}}else if(municipios&&map.hasLayer(municipios))map.removeLayer(municipios);});
document.getElementById('layer-campus').addEventListener('change',e=>{e.target.checked?campus.addTo(map):map.removeLayer(campus);});
document.getElementById('btn-home').onclick=async()=>{if(!maranhaoBounds){try{await loadMaranhao();}catch(_){}}maranhaoBounds&&maranhaoBounds.isValid()?map.fitBounds(maranhaoBounds,{padding:[15,15]}):map.setView(fallbackView.center,fallbackView.zoom);};

const fileInput=document.getElementById('geojson-file'),labStatus=document.getElementById('lab-status'),removeLocal=document.getElementById('btn-remove-geojson');document.getElementById('btn-add-geojson').onclick=()=>fileInput.click();
function clearLocal(){if(localGeojson&&map.hasLayer(localGeojson))map.removeLayer(localGeojson);localGeojson=null;fileInput.value='';removeLocal.disabled=true;labStatus.textContent='Nenhum arquivo local carregado.';labStatus.className='lab-status';}removeLocal.onclick=clearLocal;
fileInput.addEventListener('change',()=>{const file=fileInput.files[0];if(!file)return;if(file.size>10*1024*1024){labStatus.textContent='Arquivo acima de 10 MB. Otimize/generalize no QGIS antes do teste.';labStatus.className='lab-status error';fileInput.value='';return;}const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data||!['FeatureCollection','Feature','Point','MultiPoint','LineString','MultiLineString','Polygon','MultiPolygon','GeometryCollection'].includes(data.type))throw new Error('Estrutura GeoJSON não reconhecida');if(localGeojson&&map.hasLayer(localGeojson))map.removeLayer(localGeojson);localGeojson=L.geoJSON(data,{style:{color:'#a35f16',weight:2,fillColor:'#d79a52',fillOpacity:.25},pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:7,color:'#a35f16',weight:2,fillColor:'#d79a52',fillOpacity:.8}),onEachFeature:(f,l)=>bindModeAwarePopup(l,genericPopup(f.properties||{}))}).addTo(map);const b=localGeojson.getBounds();if(b.isValid())map.fitBounds(b,{padding:[20,20],maxZoom:15});removeLocal.disabled=false;const count=data.type==='FeatureCollection'?data.features.length:1;labStatus.textContent=`${file.name} · ${count} feição(ões) · camada local`;labStatus.className='lab-status success';if(maranhao&&map.hasLayer(maranhao))maranhao.bringToFront();}catch(err){console.error(err);clearLocal();labStatus.textContent='Erro: verifique se o arquivo é um GeoJSON válido em EPSG:4326.';labStatus.className='lab-status error';}};reader.onerror=()=>{labStatus.textContent='Erro ao ler o arquivo local.';labStatus.className='lab-status error';};reader.readAsText(file,'UTF-8');});
let points=[],measureLine=null,previewLine=null,labels=[],pointMarkers=[];let areaPoints=[],areaPolygon=null,areaPreview=null,areaLabel=null,areaMarkers=[];const measureButton=document.getElementById('btn-measure'),areaButton=document.getElementById('btn-area');
function distance(a,b){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng),s=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(s));}function totalDistance(){let total=0;for(let i=1;i<points.length;i++)total+=distance(points[i-1],points[i]);return total;}
function clearDistance(){points=[];if(measureLine){map.removeLayer(measureLine);measureLine=null;}if(previewLine){map.removeLayer(previewLine);previewLine=null;}labels.forEach(x=>map.removeLayer(x));labels=[];pointMarkers.forEach(x=>map.removeLayer(x));pointMarkers=[];}function clearArea(){areaPoints=[];if(areaPolygon){map.removeLayer(areaPolygon);areaPolygon=null;}if(areaPreview){map.removeLayer(areaPreview);areaPreview=null;}if(areaLabel){map.removeLayer(areaLabel);areaLabel=null;}areaMarkers.forEach(x=>map.removeLayer(x));areaMarkers=[];}
function geodesicArea(latlngs){if(latlngs.length<3)return 0;const R=6378137,rad=Math.PI/180;let area=0;for(let i=0;i<latlngs.length;i++){const p1=latlngs[i],p2=latlngs[(i+1)%latlngs.length];area+=(p2.lng-p1.lng)*rad*(2+Math.sin(p1.lat*rad)+Math.sin(p2.lat*rad));}return Math.abs(area*R*R/2);}function formatMeasuredArea(m2){if(m2<10000)return `${m2.toLocaleString('pt-BR',{maximumFractionDigits:0})} m²`;const km2=m2/1e6;if(km2<1)return `${(m2/10000).toLocaleString('pt-BR',{maximumFractionDigits:2})} ha`;return `${km2.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})} km²`;}
function setMapMode(mode){mapMode=mode;map.closePopup();const active=mode==='measure'||mode==='area';map.getContainer().classList.toggle('measure-mode',active);measureButton.classList.toggle('active-tool',mode==='measure');areaButton.classList.toggle('active-tool',mode==='area');active?map.doubleClickZoom.disable():map.doubleClickZoom.enable();if(mode!=='measure'&&previewLine){map.removeLayer(previewLine);previewLine=null;}if(mode!=='area'&&areaPreview){map.removeLayer(areaPreview);areaPreview=null;}}
function addMeasurePoint(latlng){if(mapMode!=='measure')return;points.push(latlng);pointMarkers.push(L.circleMarker(latlng,{radius:4,color:'#123f3b',weight:2,fillColor:'#fff',fillOpacity:1,interactive:false}).addTo(map));if(measureLine)map.removeLayer(measureLine);measureLine=L.polyline(points,{color:'#123f3b',weight:3,dashArray:'7,6',interactive:false}).addTo(map);if(points.length>1){const total=totalDistance();labels.push(L.tooltip({permanent:true,direction:'top',className:'measure-label'}).setLatLng(latlng).setContent(total<1?`${(total*1000).toFixed(0)} m`:`${total.toFixed(2)} km`).addTo(map));}}function addAreaPoint(latlng){if(mapMode!=='area')return;areaPoints.push(latlng);areaMarkers.push(L.circleMarker(latlng,{radius:4,color:'#123f3b',weight:2,fillColor:'#fff',fillOpacity:1,interactive:false}).addTo(map));if(areaPolygon)map.removeLayer(areaPolygon);areaPolygon=L.polygon(areaPoints,{color:'#123f3b',weight:3,fillColor:'#6eb8ad',fillOpacity:.25,interactive:false}).addTo(map);if(areaPoints.length>=3){const m2=geodesicArea(areaPoints);if(areaLabel)map.removeLayer(areaLabel);areaLabel=L.tooltip({permanent:true,direction:'center',className:'measure-label'}).setLatLng(areaPolygon.getBounds().getCenter()).setContent(`Área: ${formatMeasuredArea(m2)}`).addTo(map);}}
measureButton.onclick=()=>{if(mapMode==='measure'){setMapMode('identify');}else{clearDistance();setMapMode('measure');}};areaButton.onclick=()=>{if(mapMode==='area'){setMapMode('identify');}else{clearArea();setMapMode('area');}};document.getElementById('btn-clear').onclick=()=>{clearDistance();clearArea();setMapMode('identify');};
map.on('click',e=>{if(mapMode==='measure')addMeasurePoint(e.latlng);else if(mapMode==='area')addAreaPoint(e.latlng);});map.on('mousemove',e=>{if(mapMode==='measure'&&points.length){if(previewLine)map.removeLayer(previewLine);previewLine=L.polyline([points[points.length-1],e.latlng],{color:'#397c73',weight:2,dashArray:'4,5',opacity:.7,interactive:false}).addTo(map);}else if(mapMode==='area'&&areaPoints.length){if(areaPreview)map.removeLayer(areaPreview);areaPreview=L.polygon([...areaPoints,e.latlng],{color:'#397c73',weight:2,dashArray:'4,5',fillColor:'#6eb8ad',fillOpacity:.12,interactive:false}).addTo(map);}});map.on('dblclick',e=>{if(mapMode!=='measure'&&mapMode!=='area')return;L.DomEvent.preventDefault(e.originalEvent);L.DomEvent.stopPropagation(e);setMapMode('identify');});
document.querySelectorAll('.tool-btn[data-panel]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.panel,p=document.getElementById(id),was=p.classList.contains('open');document.querySelectorAll('.floating-panel').forEach(x=>x.classList.remove('open'));document.querySelectorAll('.tool-btn[data-panel]').forEach(x=>x.classList.remove('panel-active'));if(!was){p.classList.add('open');btn.classList.add('panel-active');}}));document.querySelectorAll('.panel-close').forEach(btn=>btn.addEventListener('click',()=>{btn.closest('.floating-panel').classList.remove('open');document.querySelectorAll('.tool-btn[data-panel]').forEach(x=>x.classList.remove('panel-active'));}));
const modal=document.getElementById('modal');document.getElementById('btn-geoai').onclick=()=>modal.hidden=false;document.getElementById('modal-close').onclick=()=>modal.hidden=true;modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true;});
document.getElementById('zoom-in').onclick=()=>map.zoomIn();document.getElementById('zoom-out').onclick=()=>map.zoomOut();

function softenGeographicGrid(){document.querySelectorAll('.graticule,.latlng-grid,.coordinate-grid').forEach(el=>{el.style.opacity='.22';el.style.strokeOpacity='.22';});}
map.on('layeradd zoomend moveend',()=>requestAnimationFrame(softenGeographicGrid));softenGeographicGrid();

function equalizeGeographicGrid(){document.querySelectorAll('.graticule,.latlng-grid,.coordinate-grid,.graticule path,.latlng-grid path,.coordinate-grid path').forEach(el=>{el.style.setProperty('opacity','.22','important');el.style.setProperty('stroke-opacity','.22','important');});}
map.on('layeradd zoomend moveend',()=>requestAnimationFrame(equalizeGeographicGrid));equalizeGeographicGrid();
